version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rest_app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydatabase
    depends_on:
      - db
    networks:
      - app_network

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: postgres_db
    ports:
      - "5432:5432"
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
