# Use the official PostgreSQL image
FROM postgres:15-alpine

# Set environment variables for the database
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_DB=mydatabase

# Expose the PostgreSQL default port
EXPOSE 5432
