services:
  node:
    image: inafkfe/nodejs2024q3-service-postgres
    env_file:
      - path: .env
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    volumes:
      - ./src:/app/src
    restart: on-failure
    develop:
      watch:
        - action: sync+restart
          path: ./src/
          target: /app/src
    networks:
      - myNetwork
  postgres:
    image: inafkfe/nodejs2024q3-service-node
    command: ' -p ${POSTGRES_PORT} -c logging_collector=on -c log_statement=all -c log_directory=logs'
    build: ./database/
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pglogs:/var/log/postgresql/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - myNetwork
networks:
  myNetwork:
    name: myNetwork
    driver: bridge
